apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: sample-ns
  labels:
    app: nginx
spec:
  replicas: 30
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: vismayavinodkk/shoplite-frontend
        ports:
        - containerPort: 80

